###
GET http://localhost:8080/users/1

###
GET http://localhost:8080/users/8/notes

###
GET http://localhost:8080/users/4/permissions

###
GET http://localhost:8080/users/4/notes/canView


###
POST http://localhost:8080/users/1/permissions
Content-Type: application/json

{
  "allowedId": 4,
  "noteId": 2,
  "canEdit": true,
  "canView": true
}

###
DELETE http://localhost:8080/users/1/permissions
Content-Type: application/json

{
  "allowedId": 4,
  "noteId": 2,
  "canEdit": false,
  "canView": false
}

###
DELETE http://localhost:8080/users/2/permissions
Content-Type: application/json

{
  "allowedId": 4,
  "noteId": 5,
  "canEdit": false,
  "canView": true
}

###
POST http://localhost:8080/users/1/notes
Content-Type: application/json

{
  "title": "New note from post",
  "content": "This is a new note for a user created with post",
  "tags": ["new tag", "Spring REST"]
}

### Incorrect note
POST http://localhost:8080/users/1/notes
Content-Type: application/json

{
  "title": "New9",
  "content": "his is a new note for a user created with post",
  "tags": ["new tag", "Spring REST"]
}

### user 4 can edit 2
PUT http://localhost:8080/users/4/notes
Content-Type: application/json

{
  "noteId": 1,
  "title": "New title to update",
  "content": "This is a edited note for a user created with post 2",
  "tags": ["Spring MVC", "Spring Boot", "informa"]
}

### user 1 owns 3
PUT http://localhost:8080/users/1/notes
Content-Type: application/json

{
  "noteId": 3,
  "title": "ÀCCC .'- :hola à Á",
  "content": "This is a edited note for a user created with post 3",
  "tags": ["pepe"]
}

###
GET http://localhost:8080/notes/2/users/canView

###
GET http://localhost:8080/notes/2/users/canEdit

###
GET http://localhost:8080/users/ratedbynotes

###
GET http://localhost:8080/users/1/notes/2/comments

###
GET http://localhost:8080/users/70/notes/2/comments

###
POST http://localhost:8080/users/1/notes/2/comments
content-type: application/json

{
  "title": "New comment from post",
  "body": "This is a comment for a note created with post"
}


### user not owner
POST http://localhost:8080/users/2/notes/2/comments
content-type: application/json

{
  "title": "New comment from post",
  "body": "This is a comment for a note created with post"
}


